bases:
  - ../../base
images:
  - name: greenstand/bulk-pack-consumer
    newTag: 1.3.3
patchesStrategicMerge:
  - bulk-pack-consumer-deployment.yaml
  - aws-key-sealed-secret.yaml
  - aws-key-id-sealed-secret.yaml
  - bulk-pack-database-connection-sealed-secret.yaml
  - sqs-url-sealed-secret.yaml
