apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-key
  namespace: bulk-pack-services
spec:
  encryptedData:
    secretAccessKey: AgC9ewF0Thn0gCQGM2fxBBlkHliHGJ0NXyPjLKPXy3FaY/SGIf96CI6crob3o6Esu+L4KXugg8a+jAOatXvX/77C1l141vI7BECg6aq1yl/07/7VE5v8Il+1CrFHeyaGjChTo41jezjjqNqfA2nyrLFWT5nT7IyBbie0k2kKUtY/HUrSdhosTHa4ZWFA/XeIF7Fue1HppoqSOi56MMeUT36hKqaMjz7hNK5KF4CrkMbc6m08dHDuixOA4YUQBES8uDUwAfZFy29NEhw7FQLuQ8VGucd8UoI8P0E9S8X8TIkIZl9XCv9NdN8yU0ppUnlzgciE/LV2bXI6PAf8JkqUoFv1rflEubPUOQduiEAN++WOamN6D4FZxw7DdSLAT0W3Tt4fqwV2sXgL/QhmdHF8UV/f0qjBWevn7VI+yvKrZzpzyhyEzdYiBOSHa9HMqmztcinDs/LiEkWYJ9EyWZU4ehjjssQsXNMuCLQ3KjM+tnrSaulaCTZ64h/JRN5z3iF2xD7qdPRefdwS6cAF6hd97NuP+xsLc2KjN0IUtdFmt5cQOmjGGXQCQ388ITncfNYr2KM9aVE7XjQSzjx+WjorIL+kjBJrbxv/b/N2C0K2Kyv98TSDR3V6sR45oI6QwgjIlcxdGTxtsWNu0uOAPPvaXMqoboi0wVpEhn2SRXe0LJ9QnXCZp0B2nWl45eImsJ5iigRPCIKm3pVZ15kRjaM5TpSFkqTlhV9sKv2MeiSaZu4viV7+bwkFM2q9
  template:
    metadata:
      creationTimestamp: null
      name: aws-key
      namespace: bulk-pack-services

