bases:
  - ../../base
patchesStrategicMerge:
  - bulk-pack-aws-key-sealed-secret.yaml
  - bulk-pack-aws-keyid-sealed-secret.yaml
  - bulk-pack-database-connection-sealed-secret.yaml
  - bulk-pack-sqs-url-sealed-secret.yaml
