apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulk-pack-consumer
  labels:
    app: bulk-pack-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulk-pack-consumer
  template:
    metadata:
      labels:
        app: bulk-pack-consumer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool
      containers:
      - name: bulk-pack-consumer
        image: greenstand/bulk-pack-consumer:latest
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: bulk-pack-database-connection
                key: db
          - name: SQS_URL
            valueFrom:
              secretKeyRef:
                name: sqs-url
                key: sqsUrl
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-key-id
                key: accessKeyId
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-key
                key: secretAccessKey
          - name: NODE_LOG_LEVEL
            value: trace
          - name: REMOTE_LOG_URL
            value: http://104.131.78.177:8000
